name: Github Auto Version

on:
  push: 
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Update version tag based on PR label
        id: release
        uses: rymndhng/release-on-push-action@v0.28.0
        with: 
          bump_version_scheme: norelease
          tag_prefix: v